version: '3.8'
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=data_base_OSM
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo/data_base_OSM

volumes:
  mongo-data:
